name: Company 4 E2E Testing

on:
  push: 
    branches: [main]
  repository_dispatch:
    types: 
      - company4-algorithm-1
      - company4-algorithm-2
      - company4-backend
  pull_request:

# Make sure URLs defined here correspond with ports defined below
env:
  BACKEND_URL: http://localhost:4000
  ALGORITHM1_URL: http://localhost:4040
  ALGORITHM2_URL: http://localhost:5000

jobs:
  integration:
    name: End to End Integration Testing
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      algorithm1:
        image: ghcr.io/seng499-company-4/company4-algorithm-1:latest
        env:
          PORT: 4040
        ports:
          - 4040:4040
      algorithm2:
        image: ghcr.io/seng499-company-4/company4-algorithm-2:latest
        env:
          PORT: 5000
        ports:
          - 5000:5000
      backend:
        image: ghcr.io/seng499-company-4/company4-backend:latest
        env:
          PORT: 4000
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
        ports:
          - 4000:4000
        # options: >-
        #   --health-cmd "curl -f http://localhost:4000/healthcheck"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
      postgres:
        # Docker Hub image
        image: postgres:14-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout shared repo 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Output repo that triggered E2E tests
        run: echo ${{ github.event.client_payload.repo }}

      - name: Checkout backend repo for DB migration
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMPANY_4_ACCESS_TOKEN }}
          repository: SENG499-Company-4/backend
          path: c4/backend

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      
      - name: Install dependencies
        run: npm ci --no-audit --no-progress

      - name: Database migrations
        run: npx -y prisma migrate dev && npx -y prisma db seed
        working-directory: c4/backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres   

      - name: Test
        env:
          BACKEND_URL: http://localhost:4000
        run: npm test