name: Company 3 E2E Testing

on:
  branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: 
      - company3-algorithm-1
      - company3-algorithm-2
      - company3-backend

# Make sure URLs defined here correspond with ports defined below
env:
  BACKEND_URL: http://localhost:4000/graphql
  ALGORITHM1_URL: http://localhost:4040
  ALGORITHM2_URL: http://localhost:5000

jobs:
  integration:
    name: End to End Integration Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared repo 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Output repo that triggered E2E tests
        run: echo ${{ github.event.client_payload.repo }}

      - name: Build all docker images (Docker Compose)
        run: docker-compose build

      - name: Start all docker images (Docker Compose)
        run: docker-compose up -d

      - name: Checkout backend repo for DB migration
        uses: actions/checkout@v3
        with:
          repository: SENG499-S22-Company3/backend
          path: c3/backend

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      
      - name: Install dependencies
        run: npm ci --no-audit --no-progress

      - name: Database migrations
        run: npx -y prisma migrate dev && npx -y prisma db seed
        working-directory: c3/backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Test
        env:
          BACKEND_URL: http://localhost:4000/graphql
        run: npm test