name: Documentation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate Swagger UI (Algorithm 1)
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/algorithm1
          spec-file: algorithm1/openapi.json
      - name: Generate Swagger UI (Algorithm 2)
        uses: Legion2/swagger-ui-action@v1
        with:
          output: dist/algorithm2
          spec-file: algorithm2/openapi.json
      - name: Generate GraphQL Documentation
        run: npx -y spectaql graphql/config.yml -t dist/graphql
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
