name: GraphQL Schema

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    name: GraphQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Lint GraphQL
        run: npx -y graphql-schema-linter graphql/schema.graphql
